includes:
- configs/hardness/base.yml

model:
  name: dimenet
  hidden_channels: 128
  num_blocks: 4
  num_bilinear: 8
  num_spherical: 7
  num_radial: 6
  cutoff: 6.0
  envelope_exponent: 5
  num_before_skip: 1
  num_after_skip: 2
  num_output_layers: 3
  max_angles_per_image: 1000000
  regress_forces: False
  use_pbc: True
  otf_graph: True

optim:
  batch_size: 2
  eval_batch_size: 2
  num_workers: 2
  lr_initial: 0.0001
  lr_gamma: 0.1
  lr_milestones:
    - 20000
    - 40000
    - 60000
  warmup_steps: 10000
  warmup_factor: 0.2
  max_epochs: 20
