includes:
- configs/hardness/base.yml

model:
  name: cgcnn
  atom_embedding_size: 128
  fc_feat_size: 256
  num_fc_layers: 4
  num_graph_conv_layers: 5
  num_gaussians: 100
  cutoff: 6.0
  regress_forces: False
  use_pbc: True

optim:
  batch_size: 64
  eval_batch_size: 64
  num_workers: 8
  lr_initial: 0.01
  lr_gamma: 0.1
  lr_milestones:
    - 781
    - 1406
    - 2031
  warmup_steps: 468
  warmup_factor: 0.2
  max_epochs: 20
