trainer: energy

dataset:
  - src: data/hardness/train/data.lmdb
    normalize_labels: True
    target_mean: 0.0
    target_std: 1.0
  - src: data/hardness/val/data.lmdb
  - src: data/hardness/test/data.lmdb

logger: tensorboard

task:
  dataset: lmdb
  description: "Crystal structure to hardness regression."
  type: regression
  metric: mae
  labels:
    - hardness
  export_predictions: True
