includes:
- configs/hardness/base.yml

model:
  name: schnet
  hidden_channels: 256
  num_filters: 128
  num_interactions: 3
  num_gaussians: 100
  cutoff: 6.0
  use_pbc: True
  regress_forces: False

optim:
  batch_size: 64
  eval_batch_size: 64
  num_workers: 8
  lr_initial: 0.005
  lr_gamma: 0.1
  lr_milestones:
    - 1562
    - 2343
    - 3125
  warmup_steps: 468
  warmup_factor: 0.2
  max_epochs: 30
